// ทดสอบวิ่งใช้งานจริงบนมือถือ (โหมดทดลองในเครื่อง): npm run build && node scripts/smoke-test.mjs
import { chromium } from 'playwright'
import { spawn } from 'node:child_process'
import fs from 'node:fs'

const PORT = 4173
const server = spawn('npx', ['vite', 'preview', '--port', String(PORT), '--strictPort'], { stdio: 'ignore' })
await new Promise((r) => setTimeout(r, 2500))
const exe = fs.existsSync('/opt/pw-browsers/chromium') ? '/opt/pw-browsers/chromium' : undefined
const browser = await chromium.launch(exe ? { executablePath: exe } : {})
const ctx = await browser.newContext({ viewport: { width: 390, height: 800 }, locale: 'th-TH' })
const page = await ctx.newPage()
const errors = []
page.on('pageerror', (e) => errors.push(String(e)))
page.on('console', (m) => m.type() === 'error' && !/fonts\.g|ERR_|Failed to load resource/.test(m.text()) && errors.push(m.text()))
const base = `http://localhost:${PORT}/`
const shot = (n) => page.screenshot({ path: `shots/${n}.png`, fullPage: true })
const go = async (hash) => { await page.goto(base + '#' + hash); await page.waitForLoadState('networkidle') }
const must = async (cond, msg) => { if (!cond) throw new Error('FAIL: ' + msg) }
// ลำดับบนจอต้องเป็น เขียว(①) → เทา(②) → แดง(③) เสมอ ทุกฟอร์ม
// ช่องกรอก ①②③ ต้องอยู่ในโซนเดียวกันติดกัน (ไม่มีรายการติ๊กแหล่งที่มาคั่นกลาง)
const oneZone = async (a, b, c) => page.evaluate(([x, y, z]) => { const zn = document.querySelector(x)?.closest('[data-zone="numbers"]'); return !!zn && zn === document.querySelector(y)?.closest('[data-zone="numbers"]') && zn === document.querySelector(z)?.closest('[data-zone="numbers"]') && !zn.querySelector('input[type="checkbox"]') }, [a, b, c])
const inOrder = async (...sel) => { const ys = []; for (const q of sel) ys.push((await page.locator(q).first().boundingBox()).y); return ys.every((y, i) => i === 0 || y > ys[i - 1]) }

const today = new Date()
const iso = (d) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
const sunday = new Date(today); sunday.setDate(today.getDate() - today.getDay())
const sun = iso(sunday)
const dmY = (d) => `${String(d.getDate()).padStart(2, '0')}/${String(d.getMonth() + 1).padStart(2, '0')}/${d.getFullYear() + 543}`

// เปิดผ่านแอป Line: ขึ้นแถบแนะนำ "เปิดใน Chrome" · เปิดด้วย Chrome ปกติ: ไม่ขึ้น
{
  const lineCtx = await browser.newContext({ viewport: { width: 390, height: 800 }, userAgent: 'Mozilla/5.0 (Linux; Android 14; SM-S911B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Mobile Safari/537.36 Line/14.9.0' })
  const lp = await lineCtx.newPage()
  await lp.goto(base + '#/')
  await must(await lp.getByRole('link', { name: 'เปิดใน Chrome' }).isVisible(), 'Line in-app browser shows the open-in-Chrome banner')
  await lineCtx.close()
}
await go('/')
await must((await page.getByRole('link', { name: 'เปิดใน Chrome' }).count()) === 0, 'no in-app banner in a normal browser')
await must(await page.getByText('โหมดทดลองคนเดียว').isVisible(), 'solo banner')
await shot('01-home-empty')

// ตั้งค่า: บัญชี + ประเภทถวาย
await go('/settings')
await page.getByLabel('ชื่อบัญชี').fill('บัญชีหลัก')
await page.getByLabel('ธนาคาร', { exact: true }).fill('กสิกรไทย')
await page.getByLabel('เลขท้าย 4 ตัว').fill('1234')
await page.getByRole('button', { name: 'เพิ่มบัญชี' }).click()
await page.getByLabel('ชื่อประเภทถวายใหม่').fill('ถวายค่าไฟ')
await page.getByRole('button', { name: 'เพิ่ม', exact: true }).click()
await must(await page.getByText('ถวายค่าไฟ').first().isVisible(), 'custom income type')
await shot('02-settings')

// รายรับโอน (มีเลขอ้างอิง + เลขสมาชิก)
await go('/income')
await page.getByRole('button', { name: '＋ บันทึกรายรับ' }).click()
await page.getByLabel('จำนวนเงิน (บาท)').fill('1500')
await page.getByLabel('เลขอ้างอิงการโอน').fill('REF123456')
await page.getByLabel(/เลขสมาชิก/).fill('1348')
await page.getByRole('button', { name: 'บันทึก', exact: true }).click()
await must(await page.getByText('อ้างอิง REF123456').isVisible(), 'income transfer saved with ref')
await must(await page.getByText('สมาชิก 1348').isVisible(), 'member no saved')
await shot('03-income')

// งบประมาณ: ตั้งงบใหม่ (3 ช่อง) · งบที่ยังไม่ตั้งแท่งกลาง · บันทึกตรง · งบมาตรฐาน · งบฉุกเฉิน
await go('/budget')
await page.getByRole('button', { name: '＋ ตั้งงบใหม่' }).click()
await page.getByLabel('ชื่องบ', { exact: true }).fill('ค่าสวัสดิการผู้รับใช้')
await must(await inOrder('.sheet fieldset', '#nb-got', '#nb-bud', '#nb-sp') && await oneZone('#nb-got', '#nb-bud', '#nb-sp'), 'new budget form: sources, then ①②③ together in one zone')
await page.getByLabel(/ได้รับ \(แท่งเขียว\)/).fill('20000')
await page.getByLabel(/งบที่ตั้ง \(แท่งเทา\)/).fill('50000')
await page.getByLabel(/จ่ายแล้ว \(แท่งแดง\)/).fill('5000')
await must((await page.locator('.sheet svg[aria-label*="งบที่ตั้ง 50,000.00"]').count()) === 1, 'live preview shows the budget bar')
await page.getByRole('button', { name: 'บันทึกงบ' }).click()
await page.locator('svg[aria-label*="ค่าสวัสดิการผู้รับใช้: ได้รับ 20,000.00 บาท, งบที่ตั้ง 50,000.00 บาท, จ่ายแล้ว 5,000.00"]').waitFor({ state: 'attached' })
// เพิ่มรายจ่ายตรง 3,000 → แท่งแดงรวมเป็น 8,000 (หักลบจริง)
await page.locator('section[aria-label="งบ ค่าสวัสดิการผู้รับใช้"]').getByRole('button', { name: '＋ ใช้จ่าย' }).click()
await page.getByLabel('จำนวนเงิน (บาท)').fill('3000')
await page.getByRole('button', { name: 'บันทึก', exact: true }).click()
await page.locator('svg[aria-label*="ค่าสวัสดิการผู้รับใช้: ได้รับ 20,000.00 บาท, งบที่ตั้ง 50,000.00 บาท, จ่ายแล้ว 8,000.00"]').waitFor({ state: 'attached' })
// แตะแท่งเขียวเพื่อแก้ตัวเลข: ยกมา 25,000 และงบที่ตั้งเป็น 60,000 (แท่งกลางแก้ตรง ๆ แล้วลงประวัติเอง)
await page.locator('section[aria-label="งบ ค่าสวัสดิการผู้รับใช้"]').getByRole('button', { name: 'แก้ตัวเลขแท่ง ได้รับ' }).click()
await must(await inOrder('.sheet fieldset', '#ed-in', '#ed-bud', '#ed-out') && await oneZone('#ed-in', '#ed-bud', '#ed-out'), 'edit budget form: ①②③ together')
await page.getByLabel(/① ได้รับ/).fill('25000')
await page.getByLabel(/② งบที่ตั้ง/).fill('60000')
await page.getByRole('button', { name: 'บันทึก', exact: true }).click()
await page.locator('svg[aria-label*="ค่าสวัสดิการผู้รับใช้: ได้รับ 25,000.00 บาท, งบที่ตั้ง 60,000.00 บาท, จ่ายแล้ว 8,000.00"]').waitFor({ state: 'attached' })
// กองทุนที่มีเงินแล้วแต่ยังไม่ตั้งงบ: เขียว = เงินที่มี · กลางติดพื้น
await page.getByRole('button', { name: '＋ ตั้งงบใหม่' }).click()
await page.getByLabel('ชื่องบ', { exact: true }).fill('กองทุนสุสาน')
await page.getByLabel(/ได้รับ \(แท่งเขียว\)/).fill('100000')
await page.getByRole('button', { name: 'บันทึกงบ' }).click()
await page.locator('svg[aria-label*="กองทุนสุสาน: ได้รับ 100,000.00 บาท, งบที่ตั้ง 0.00 บาท, จ่ายแล้ว 0.00"]').waitFor({ state: 'attached' })
// ลบงบ → หายจากหน้า → กู้คืนได้ → ลบอีกครั้ง
page.once('dialog', (d) => d.accept())
await page.getByRole('button', { name: 'ลบงบ กองทุนสุสาน' }).click()
await page.locator('svg[aria-label*="กองทุนสุสาน:"]').waitFor({ state: 'detached' })
await page.getByText(/งบที่ลบแล้ว \(1\)/).click()
await page.getByRole('button', { name: /กู้คืน/ }).click()
await page.locator('svg[aria-label*="กองทุนสุสาน:"]').waitFor({ state: 'attached' })
page.once('dialog', (d) => d.accept())
await page.getByRole('button', { name: 'ลบงบ กองทุนสุสาน' }).click()
await page.locator('svg[aria-label*="กองทุนสุสาน:"]').waitFor({ state: 'detached' })
// ลบถาวร: เอางบที่ลบแล้วออกจากไฟล์จริง
page.once('dialog', (d) => d.accept())
await page.getByText(/งบที่ลบแล้ว \(1\)/).click()
await page.getByRole('button', { name: 'ลบถาวร กองทุนสุสาน' }).click()
await page.getByText(/งบที่ลบแล้ว/).waitFor({ state: 'detached' })
await page.getByRole('button', { name: '＋ เลือกจากรายการแนะนำ' }).click()
await page.getByRole('checkbox', { name: 'สาธารณูปโภค' }).check()
await page.getByRole('button', { name: 'เพิ่ม 1 หมวดที่เลือก' }).click()
await page.locator('svg[aria-label*="สาธารณูปโภค:"]').waitFor({ state: 'attached' })
await must((await page.locator('figure.chart svg[aria-label*="งบที่ตั้ง"]').count()) === 3, 'only the cards the user made exist (overview + 2)')
await page.getByRole('button', { name: '🚨 เพิ่มงบฉุกเฉิน' }).click()
await page.getByLabel('จำนวนเงิน (บาท)').fill('50000')
await page.getByLabel(/เหตุผล/).fill('มติที่ประชุม')
await page.getByRole('button', { name: 'บันทึก', exact: true }).click()
await page.getByText('ประวัติการปรับงบ (2)').waitFor()
await page.getByRole('button', { name: '± ปรับงบ' }).click()
await page.getByLabel('หมวด', { exact: true }).selectOption({ index: 0 })
await page.getByLabel('จำนวนเงิน (บาท)').fill('20000')
await page.getByLabel(/เหตุผล/).fill('ตั้งงบเพิ่ม')
await page.getByRole('button', { name: 'บันทึก', exact: true }).click()
await page.getByText('ประวัติการปรับงบ (3)').waitFor()
await must((await page.locator('figure.chart svg[aria-label*="งบที่ตั้ง"]').count()) >= 3, 'every budget line has the 3-bar chart (+ overview)')
await page.getByRole('button', { name: /✎ แก้ไขงบ/ }).first().click()
await page.getByLabel('ชื่องบ', { exact: true }).fill('เงินเดือนผู้รับใช้')
await page.getByRole('checkbox', { name: /^สิบลด/ }).check()
await page.getByRole('button', { name: 'บันทึก', exact: true }).click()
await must(await page.getByText('เงินเดือนผู้รับใช้').first().isVisible(), 'budget renamed')
await must(await page.getByText(/แหล่งที่มาของเงิน: สิบลด/).first().isVisible(), 'income type linked to budget line')
// เพิ่ม / แก้ชื่อ / ลบ แหล่งที่มาในฟอร์มเดียวกับรายการติ๊ก
await page.getByRole('button', { name: /✎ แก้ไขงบ/ }).first().click()
await page.getByLabel('ชื่อแหล่งที่มาใหม่').fill('ถวายสวัสดิการผู้รับใช้')
await page.getByRole('button', { name: '＋ เพิ่ม', exact: true }).click()
await must(await page.getByRole('checkbox', { name: /^ถวายสวัสดิการผู้รับใช้/ }).isChecked(), 'new source added and ticked')
page.once('dialog', (d) => d.accept('ถวายสวัสดิการ'))
await page.getByRole('button', { name: 'แก้ชื่อ ถวายสวัสดิการผู้รับใช้' }).click()
await page.getByRole('checkbox', { name: /^ถวายสวัสดิการ/ }).waitFor()
page.once('dialog', (d) => d.accept())
await page.getByRole('button', { name: 'ลบ ถวายสวัสดิการ' }).click()
await page.getByRole('checkbox', { name: /^ถวายสวัสดิการ/ }).waitFor({ state: 'detached' })
await page.getByRole('button', { name: 'บันทึก', exact: true }).click()
await shot('04-budget')

// กองทุน: เป้าหมาย 6 ล้าน · เงินถวายเข้ากองทุนผ่านประเภทถวาย · ใช้จ่ายตรง · ลบ
await go('/budget')
await page.getByRole('button', { name: 'กองทุน (สะสม)' }).click()
await page.getByRole('button', { name: '＋ ตั้งกองทุนใหม่' }).click()
await page.getByLabel('ชื่อกองทุน', { exact: true }).fill('กองทุนซื้อที่ดิน')
await must(await inOrder('.sheet fieldset', '#nf-got', '#nf-target', '#nf-sp') && await oneZone('#nf-got', '#nf-target', '#nf-sp'), 'new fund form: sources, then ①②③ together in one zone')
await page.getByLabel(/② เป้าหมาย/).fill('6000000')
await page.getByRole('button', { name: 'บันทึกกองทุน' }).click()
await page.locator('svg[aria-label*="กองทุนซื้อที่ดิน: เก็บได้ 0.00 บาท, เป้าหมาย 6,000,000.00 บาท, จ่ายแล้ว 0.00"]').waitFor({ state: 'attached' })
// บันทึกเงินถวายเข้ากองทุนจากหน้ารายรับ: ประเภทถวาย = กองทุนซื้อที่ดิน
await go('/income')
await page.getByRole('button', { name: '＋ บันทึกรายรับ' }).click()
await page.getByLabel('จำนวนเงิน (บาท)').fill('250000')
await page.getByLabel(/ประเภทถวาย/).selectOption({ label: 'กองทุนซื้อที่ดิน' })
await page.getByRole('button', { name: 'บันทึก', exact: true }).click()
await page.getByText('กองทุนซื้อที่ดิน').first().waitFor()
await go('/budget')
await page.getByRole('button', { name: 'กองทุน (สะสม)' }).click()
await page.locator('svg[aria-label*="กองทุนซื้อที่ดิน: เก็บได้ 250,000.00 บาท, เป้าหมาย 6,000,000.00 บาท, จ่ายแล้ว 0.00"]').waitFor({ state: 'attached' })
await page.locator('section[aria-label="กองทุน กองทุนซื้อที่ดิน"]').getByRole('button', { name: '＋ ใช้จ่าย' }).click()
await page.getByLabel('จำนวนเงิน (บาท)').fill('50000')
await page.getByRole('button', { name: 'บันทึก', exact: true }).click()
await page.locator('svg[aria-label*="กองทุนซื้อที่ดิน: เก็บได้ 250,000.00 บาท, เป้าหมาย 6,000,000.00 บาท, จ่ายแล้ว 50,000.00"]').waitFor({ state: 'attached' })
await must(await page.getByText(/ขาดอีก 5,750,000 ถึงเป้าหมาย/).isVisible(), 'fund shows the shortfall to target')
await page.getByRole('button', { name: /✎ แก้ไขกองทุน/ }).first().click()
await must(await inOrder('.sheet fieldset', '#ef-in', '#ef-target', '#ef-out') && await oneZone('#ef-in', '#ef-target', '#ef-out'), 'edit fund form: ①②③ together')
await page.getByRole('button', { name: 'ปิด' }).click()
await shot('04b-fund')
// ใบเบิกเลือกกองทุนเป็นหมวดได้
await go('/vouchers')
await page.getByRole('button', { name: '＋ ทำใบเบิก' }).click()
await must((await page.locator('#v-l0 optgroup[label="กองทุน"] option').count()) === 1, 'fund offered in the voucher form')
await page.getByRole('button', { name: 'ปิด' }).click()
// สร้างกองทุนที่ 2 แล้วลบ → ประเภทถวายที่สร้างคู่กันหายจากช่องเลือก
await go('/budget')
await page.getByRole('button', { name: 'กองทุน (สะสม)' }).click()
await page.getByRole('button', { name: '＋ ตั้งกองทุนใหม่' }).click()
await page.getByLabel('ชื่อกองทุน', { exact: true }).fill('กองทุนสร้างอาคาร')
await page.getByRole('button', { name: 'บันทึกกองทุน' }).click()
await page.locator('svg[aria-label*="กองทุนสร้างอาคาร:"]').waitFor({ state: 'attached' })
page.once('dialog', (d) => d.accept())
await page.getByRole('button', { name: 'ลบกองทุน กองทุนสร้างอาคาร' }).click()
await page.locator('svg[aria-label*="กองทุนสร้างอาคาร:"]').waitFor({ state: 'detached' })
await go('/income')
await page.getByRole('button', { name: '＋ บันทึกรายรับ' }).click()
await must((await page.getByLabel(/ประเภทถวาย/).locator('option', { hasText: 'กองทุนสร้างอาคาร' }).count()) === 0, 'deleted fund type is no longer selectable')
await page.getByRole('button', { name: 'ปิด' }).click()

// ใบบันทึกการถวายวันอาทิตย์ (ตู้ถวาย + โอน)
await go(`/rounds/${sun}`)
await page.locator('#e-tt1').fill('6'); await page.locator('#l-tt1').fill('3000')
await page.locator('#e-tt2').fill('7'); await page.locator('#l-tt2').fill('2000')
await page.getByRole('button', { name: 'บันทึกยอดตู้ถวาย' }).click()
await page.getByRole('button', { name: /ฉันนับซ้ำแล้ว/ }).waitFor()
await page.getByRole('button', { name: /ฉันนับซ้ำแล้ว/ }).click()
await page.getByText('ยืนยันแล้วโดย').waitFor()
// เงินโอนในสัปดาห์: ลงเป็นยอดรวมก้อนเดียว 1,500 ไม่แยกประเภท (เหมือนใบกระดาษจริง) — ในสมุดจะเป็น 2 รายการ 1,000 + 500
for (const [i, amt] of ['1500'].entries()) {
  await page.getByRole('button', { name: '＋ บันทึกรายการโอน' }).click()
  await page.getByLabel('จำนวนเงิน (บาท)').fill(amt)
  await page.getByLabel(/ประเภทถวาย/).selectOption({ label: 'โอน (ยังไม่แยกประเภท)' })
  await page.getByRole('button', { name: 'บันทึก', exact: true }).click()
  await page.getByText(`รวมจากการโอน (${i + 1} รายการ)`, { exact: true }).waitFor()
}
await must(await page.getByText('รวมจากการโอน (1 รายการ)', { exact: true }).isVisible(), 'transfer total listed in the sunday sheet')
await page.getByLabel('ยอดที่ฝาก (บาท)', { exact: false }).fill('5000')
await page.getByRole('button', { name: 'บันทึกการนำฝาก' }).click()
await must(await page.getByText('ยอดฝากตรงกับยอดตู้ถวาย').isVisible(), 'deposit matches')
await must((await page.getByText('ใบบันทึกการถวาย', { exact: false }).count()) > 0, 'printable sheet exists')
await shot('05-round')
await go('/income')
await must(await page.getByText('รอบนับ').first().isVisible(), 'round income appears in income list')

// สมุด/สเตตเมนต์: CSV (ฝากเงินสด 5,000 + โอนเข้า 2 รายการ รวม 1,500 = ยอดโอนรวมของสัปดาห์) + ค่าธรรมเนียม
const csv = `วันที่,รายการ,ถอน,ฝาก,ยอดคงเหลือ\n${dmY(sunday)},ฝากเงินสด,,"5,000.00","5,000.00"\n${dmY(sunday)},TN โอนเข้า,,"1,000.00","6,000.00"\n${dmY(sunday)},TN โอนเข้า,,"500.00","6,500.00"\n${dmY(sunday)},ค่าธรรมเนียม,10.00,,"6,490.00"\n${dmY(sunday)},โอนเข้า ไม่มีสลิป,,777.00,"7,267.00"\n`
fs.mkdirSync('shots', { recursive: true }); fs.writeFileSync('shots/stmt.csv', csv)
await go('/rounds/statement')
await page.getByRole('button', { name: '⬆️ ไฟล์ CSV/รูป' }).click()
await page.getByLabel(/ไฟล์ \(CSV/).setInputFiles('shots/stmt.csv')
await page.getByText('อ่านได้ 5 รายการ').waitFor()
await shot('06-upload')
await page.getByRole('button', { name: 'นำเข้า 5 รายการ' }).click()
await page.getByText(/นำเข้า 5 รายการใหม่/).waitFor()
await page.getByRole('button', { name: 'ปิด' }).click()
await page.getByRole('button', { name: 'ยอมรับทั้งหมด' }).click()           // ฝากเงินสด ↔ ยอดฝาก
await page.getByText(/รวมกันได้เท่ากับยอดโอนรวมในใบถวาย 1 สัปดาห์/).waitFor() // โอน 2 รายการ ↔ ยอดโอนรวมสัปดาห์
await page.getByRole('button', { name: 'ยอมรับ', exact: true }).click()
await page.getByRole('button', { name: 'ทั้งหมด', exact: true }).click()
await page.getByText(/ยอดโอนรวมใบถวาย/).first().waitFor()
await page.getByRole('button', { name: 'ยังไม่จับคู่', exact: true }).click()
await shot('07-statement-matched')
// เงินเข้า 777 ไม่มีสลิป → รับเป็น "ไม่ทราบที่มา" (นับเป็นรายรับ ไม่ทิ้ง)
await must(await page.getByText(/เงินเข้าในสมุด 1 รายการ/).isVisible(), 'unknown inflow banner')
await page.getByRole('button', { name: /รับทั้งหมดเป็น/ }).click()
await page.getByText(/เงินเข้าในสมุด 1 รายการ/).waitFor({ state: 'detached' })
await page.getByRole('button', { name: 'จับคู่เอง…' }).click()
await page.getByLabel('คำอธิบาย').fill('ค่าธรรมเนียมธนาคาร')
await page.getByRole('button', { name: 'บันทึกว่าเป็นรายการอื่น' }).click()
await must(await page.getByText('จับคู่ครบทุกรายการแล้ว').isVisible(), 'all matched')
await go('/income')
await must(await page.getByText(/ไม่ทราบที่มา — แตะเพื่อระบุที่มา/).isVisible(), 'unknown income appears in income list')
await go('/rounds/statement')
// พิมพ์รายการจากสมุดเอง: ดอกเบี้ย (IN) จับคู่อัตโนมัติ
await page.getByRole('button', { name: '✍️ พิมพ์รายการจากสมุด' }).click()
await page.getByLabel('รายการ', { exact: true }).selectOption('IN')
await page.getByLabel(/ฝาก\/เข้า/).fill('84.14')
await page.getByRole('button', { name: 'บันทึกรายการ' }).click()
await page.getByText(/บันทึกแล้ว ✓ \(1 รายการ\)/).waitFor()
await page.getByRole('button', { name: 'เสร็จ' }).click()
await shot('07b-statement-manual')

// ใบเบิก 2 รายการ (รวม 3,500 เกินเกณฑ์ 2,000 → อนุมัติ 2 ขั้น)
await go('/vouchers')
await page.getByRole('button', { name: '＋ ทำใบเบิก' }).click()
await page.locator('#v-d0').fill('ซื้อหลอดไฟ'); await page.locator('#v-a0').fill('3000'); await page.locator('#v-l0').selectOption({ index: 2 })
await page.getByRole('button', { name: '＋ เพิ่มรายการ' }).click()
await page.locator('#v-d1').fill('ค่าอินเตอร์เน็ต (บิล 27-9-69)'); await page.locator('#v-a1').fill('500'); await page.locator('#v-m1').selectOption('advance')
await page.getByRole('button', { name: 'ยื่นใบเบิก' }).click()
await page.getByText(/ซื้อหลอดไฟ และอีก 1 รายการ/).first().click()
page.once('dialog', (d) => d.accept(''))
await page.getByRole('button', { name: '✓ อนุมัติ' }).click()
await page.getByText('การอนุมัติ (1/2)').waitFor()
page.once('dialog', (d) => d.accept(''))
await page.getByRole('button', { name: '✓ อนุมัติ' }).click()
await page.getByText('การอนุมัติ (2/2)').waitFor()
await page.getByRole('button', { name: '💸 บันทึกการจ่ายเงิน' }).click()
await page.getByRole('button', { name: 'บันทึกการจ่าย', exact: true }).click()
await page.getByText('จ่ายแล้ว รอใบเสร็จ').first().waitFor()
await must((await page.getByText('ใบเบิก - จ่ายเงิน', { exact: false }).count()) > 0, 'printable voucher form exists')
await shot('08-voucher')
await go('/vouchers')
await must(await page.getByText('จ่ายแล้ว รอใบเสร็จ').first().isVisible(), 'weekly summary shows stage')
await shot('09-vouchers')

// รายงาน
await go('/reports')
await page.getByRole('button', { name: 'รายปี' }).click()
await page.getByText('รายรับแยกตามประเภทถวาย').first().waitFor()
await must((await page.locator('figure.chart svg').count()) >= 3, 'charts rendered')
await shot('10-report-year')
await page.emulateMedia({ media: 'print' })
await page.pdf({ path: 'shots/report.pdf', format: 'A4' })
await page.emulateMedia({ media: 'screen' })
// ล้างข้อมูลทดสอบทั้งปี → ทุกหน้าว่างสะอาด (ผู้ใช้/ตั้งค่า/บัญชีคงอยู่)
await go('/settings')
await page.getByRole('checkbox', { name: /ล้างกองทุนทั้งหมดด้วย/ }).check()
await page.locator('#cl-word').fill('ล้างข้อมูล')
await page.getByRole('button', { name: /^ล้างข้อมูลปี/ }).click()
await page.getByText(/ล้างข้อมูลปี .* เรียบร้อย/).waitFor()
await go('/income')
await must(await page.getByText('ยังไม่มีรายรับ').isVisible(), 'income cleared')
await go('/budget')
await page.getByRole('button', { name: 'กองทุน (สะสม)' }).click()
await must(await page.getByText(/ยังไม่มีกองทุน/).isVisible(), 'funds cleared')
await page.getByRole('button', { name: 'งบประมาณ (รายปี)' }).click()
await must(await page.getByText(/ยังไม่มีงบประมาณปี/).isVisible(), 'budget cleared')
await go('/settings')
await must(await page.getByText('บัญชีหลัก').first().isVisible(), 'bank accounts kept after clean')
await go('/')
await shot('11-home')
await page.setViewportSize({ width: 390, height: 800 })
// ความกว้างล้นจอ
const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)
await must(!overflow, 'no horizontal overflow on home')

await browser.close(); server.kill()
if (errors.length) { console.error('console errors:\n' + errors.join('\n')); process.exit(1) }
console.log('SMOKE OK')
